export const EMPLOYEES = [
  {
    id: "1",
    name: "Julian Alessandro",
    role: "Usta Berber",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCuwuER9xpH95fp-meVaDyN_z-USwzjZDkhy7diLqE9Z6dPqFVa6C4TqO96oX4wXxfgbOhWwApgJtW6a4v1qBpNE-ZoLNF9pNzUOz5LdaQk8ZoJCoVTxSwMte28wy80_zsUZmhX0tcSs3ZwAS6Vkj_Q-eAIJ9hdLuLEJYTIe94bHvmMEfhF60OinPdqWIyXRAZApKY0iP2UuyIPF-cuONYXmEQ1mLgi4pa1ZlGTHIWQeTADI2YvwcYtEcL5D4ajzA3c5_LW9BZ6isY",
    bio: "12 yili askin luks bakim deneyimiyle klasik makas teknikleri ve modern precision fade kesimlerinde uzmanlasmistir.",
    phone: "+90 555 210 44 10",
    email: "julian@burandevu.com",
    schedule: "Pzt - Cmt | 10:00 - 20:00",
    experience: "12 yil",
    rating: "4.9",
    todayAppointments: 9,
    completedThisWeek: 42,
    totalBookings: "1,240",
    totalRevenue: "₺45.5k",
    location: "Nisantasi Atelier, Abdi Ipekci Cd. No:42, Istanbul",
    availability: "Musait",
    specialties: ["Skin Fade", "Sakal Tasarimi", "VIP Bakim"],
    services: [
      { id: "s1", title: "Royal Sac Kesimi", duration: "60 Dk", price: "₺450" },
      { id: "s2", title: "Sakal Sekillendirme", duration: "30 Dk", price: "₺250" },
      { id: "s3", title: "Usta Bakim Kombosu", duration: "90 Dk", price: "₺600" },
      { id: "s4", title: "Sac Derisi Terapisi", duration: "45 Dk", price: "₺350" },
    ],
    workingHours: [
      { day: "Pazartesi", hours: "09:00 — 18:00" },
      { day: "Salı", hours: "09:00 — 18:00" },
      { day: "Çarşamba", hours: "09:00 — 18:00" },
      { day: "Perşembe", hours: "09:00 — 18:00" },
      { day: "Cuma", hours: "09:00 — 18:00" },
      { day: "Cumartesi", hours: "Kapalı", closed: true },
    ],
    recentAppointments: [
      { id: "a1", client: "Emir A.", service: "Skin Fade", time: "10:30" },
      { id: "a2", client: "Mete K.", service: "Sac + Sakal", time: "13:00" },
      { id: "a3", client: "Can B.", service: "Bakim Paketi", time: "16:15" },
    ],
  },
  {
    id: "2",
    name: "Elena Rodriguez",
    role: "Renk Uzmani",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDad3jniGezsFAC7yDvGb4gxGSyhenzyGnDLGdmdhQQWnRWeYHKTDn3-fRNZ99ZQ0MgITZNtq7EoAfGWNigwo_N5CMj1ZOTh7U3-6ozalmjS6FFvbUvozCvkqbEmdntjCNkrKFzoGFwYkyNx3evQB5A28briHB5HfPVyDsaTlj5S7jelLCUA97sttUszAz-bjvDLuq1mDaRxnQEfuj2YBK_KAnzh8li27BzNEReOZSZWIyPVvzLH8oZmFgNUMgEQ-Crev3s8EZ8XD8",
    bio: "Renk donusumu, gloss uygulamasi ve kadin kesimlerinde yuksek musteri memnuniyetiyle one cikiyor.",
    phone: "+90 555 210 44 11",
    email: "elena@burandevu.com",
    schedule: "Sal - Paz | 11:00 - 21:00",
    experience: "6 yil",
    rating: "4.8",
    todayAppointments: 7,
    completedThisWeek: 35,
    totalBookings: "980",
    totalRevenue: "₺38.2k",
    location: "Nisantasi Atelier, Istanbul",
    availability: "Musait",
    specialties: ["Balayage", "Gloss", "Women Cut"],
    services: [
      { id: "s1", title: "Signature Balayage", duration: "120 Dk", price: "₺1.250" },
      { id: "s2", title: "Gloss Bakimi", duration: "45 Dk", price: "₺380" },
      { id: "s3", title: "Precision Kesim", duration: "60 Dk", price: "₺520" },
      { id: "s4", title: "Renk Tazeleme", duration: "75 Dk", price: "₺690" },
    ],
    workingHours: [
      { day: "Pazartesi", hours: "Kapalı", closed: true },
      { day: "Salı", hours: "11:00 — 21:00" },
      { day: "Çarşamba", hours: "11:00 — 21:00" },
      { day: "Perşembe", hours: "11:00 — 21:00" },
      { day: "Cuma", hours: "11:00 — 21:00" },
      { day: "Cumartesi", hours: "11:00 — 20:00" },
    ],
    recentAppointments: [
      { id: "a1", client: "Selin D.", service: "Balayage", time: "11:00" },
      { id: "a2", client: "Ece T.", service: "Gloss", time: "14:30" },
      { id: "a3", client: "Doga Y.", service: "Katli Kesim", time: "18:00" },
    ],
  },
  {
    id: "3",
    name: "Marcus Thorne",
    role: "Sakal Uzmani",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuB2DMo2PmW_wkOMe6oejK1zoAMYSqSZOBxB0mx0HAEUef8iT2nNeYiP1UIBfRJzNH6NqKT-skNyaEY0n47siS_lIyULtzFY9YDLw6ECGWc0gseRD-u-mGGqdgKdZTW1kvEZB187iCm6Jh7yJPNNq0F6dpSu7mOPs0OeSq4yDwu7UhN4zAAHTZMnL2j-ksJD_04YAMvIHjSbNj1eC59f1ZDrauHWXb-BXMqcO8C8esIIYjicc6qIq-WlcOqbm1Q-fcaCXpEz9R3VAKc",
    bio: "Detayci sakal form verme ve cilt hassasiyetine uygun bakim protokolleriyle taniniyor.",
    phone: "+90 555 210 44 12",
    email: "marcus@burandevu.com",
    schedule: "Pzt - Cum | 09:00 - 18:00",
    experience: "5 yil",
    rating: "4.7",
    todayAppointments: 6,
    completedThisWeek: 29,
    totalBookings: "840",
    totalRevenue: "₺29.8k",
    location: "Nisantasi Atelier, Istanbul",
    availability: "Musait",
    specialties: ["Hot Towel", "Line Up", "Cilt Bakimi"],
    services: [
      { id: "s1", title: "Sakal Ritueli", duration: "40 Dk", price: "₺290" },
      { id: "s2", title: "Precision Line Up", duration: "25 Dk", price: "₺190" },
      { id: "s3", title: "Deluxe Sicak Havlu", duration: "50 Dk", price: "₺340" },
      { id: "s4", title: "Erkek Cilt Bakimi", duration: "45 Dk", price: "₺320" },
    ],
    workingHours: [
      { day: "Pazartesi", hours: "09:00 — 18:00" },
      { day: "Salı", hours: "09:00 — 18:00" },
      { day: "Çarşamba", hours: "09:00 — 18:00" },
      { day: "Perşembe", hours: "09:00 — 18:00" },
      { day: "Cuma", hours: "09:00 — 18:00" },
      { day: "Cumartesi", hours: "Kapalı", closed: true },
    ],
    recentAppointments: [
      { id: "a1", client: "Yigit P.", service: "Line Up", time: "09:30" },
      { id: "a2", client: "Hakan S.", service: "Hot Towel", time: "12:45" },
      { id: "a3", client: "Tolga I.", service: "Bakim", time: "15:40" },
    ],
  },
  {
    id: "4",
    name: "Sophia Lee",
    role: "Stilist",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBhEIfD06lCgaJGXfVIZkTQe_Ah8WvrAKIYTpQ8KRGic7nkZnPKGh3e6YrafBWKx3x4Biw7H3REE9wcebczHHAm2C6P7mvIrRSiXU_8YuqFAKB0aNQSD7lx4809zn-MdnHTN5Pdz8b7K0EUJNgthLgkdtEcDHxgt7P144sI6IHZySzb6Yx1dcHRPAwtsZFTTgp45QN-ExjCrVbl0U4mTxiHir7-zZin32hxy2rEDNC_r-tpRF5aOzBcJCjlFec_L8IRgX8lYuQYrE4",
    bio: "Gunluk styling, firin ve event hazirliklarinda hizli ve duzgun teslim sunuyor.",
    phone: "+90 555 210 44 13",
    email: "sophia@burandevu.com",
    schedule: "Pzt - Paz | 12:00 - 20:00",
    experience: "4 yil",
    rating: "4.8",
    todayAppointments: 8,
    completedThisWeek: 33,
    totalBookings: "910",
    totalRevenue: "₺34.1k",
    location: "Nisantasi Atelier, Istanbul",
    availability: "Musait",
    specialties: ["Blow Dry", "Event Styling", "Women Cut"],
    services: [
      { id: "s1", title: "Etkinlik Stili", duration: "70 Dk", price: "₺540" },
      { id: "s2", title: "Firin", duration: "35 Dk", price: "₺260" },
      { id: "s3", title: "Kadin Kesimi", duration: "55 Dk", price: "₺460" },
      { id: "s4", title: "Hacim Bitisi", duration: "40 Dk", price: "₺310" },
    ],
    workingHours: [
      { day: "Pazartesi", hours: "12:00 — 20:00" },
      { day: "Salı", hours: "12:00 — 20:00" },
      { day: "Çarşamba", hours: "12:00 — 20:00" },
      { day: "Perşembe", hours: "12:00 — 20:00" },
      { day: "Cuma", hours: "12:00 — 20:00" },
      { day: "Cumartesi", hours: "12:00 — 18:00" },
    ],
    recentAppointments: [
      { id: "a1", client: "Melis C.", service: "Styling", time: "12:00" },
      { id: "a2", client: "Sena U.", service: "Firin", time: "15:00" },
      { id: "a3", client: "Nehir K.", service: "Kesim", time: "18:20" },
    ],
  },
  {
    id: "5",
    name: "David Brooks",
    role: "Junior Berber",
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCf3xu5pzPE7eXmOo4WSDm_AKkjpBInbmnsKhdAPPjztggFxOfeDLVTZXul39pKvGbG4fPia8ANi2LDSlB6IW5tMrnB3WXLDY3oy4w_B-iyvyrdAPx6NOLD_FpyGHURlgoBC0RT04eyzamAzZsu8JARoQlky8wltK1n8GKNrnTt-guhnMEWiCVIUjaagOkBAYm0D6CuJ5Ky9W4G_NlUSfYPTuEGV2W2DOBoVI_8elo0oD5p_xPjyp1gOha22yaxHkAKpVu5mijN0qM",
    bio: "Hizli kesim ve musteri karsilama sureclerinde operasyonu destekleyen enerjik ekip uyesi.",
    phone: "+90 555 210 44 14",
    email: "david@burandevu.com",
    schedule: "Sal - Paz | 10:00 - 19:00",
    experience: "2 yil",
    rating: "4.6",
    todayAppointments: 5,
    completedThisWeek: 24,
    totalBookings: "510",
    totalRevenue: "₺18.7k",
    location: "Nisantasi Atelier, Istanbul",
    availability: "Musait",
    specialties: ["Buzz Cut", "Sac Yikama", "Hizli Servis"],
    services: [
      { id: "s1", title: "Buzz Cut", duration: "25 Dk", price: "₺180" },
      { id: "s2", title: "Klasik Kesim", duration: "40 Dk", price: "₺260" },
      { id: "s3", title: "Yikama ve Sekillendirme", duration: "20 Dk", price: "₺140" },
      { id: "s4", title: "Hizli Bakim", duration: "30 Dk", price: "₺200" },
    ],
    workingHours: [
      { day: "Pazartesi", hours: "Kapalı", closed: true },
      { day: "Salı", hours: "10:00 — 19:00" },
      { day: "Çarşamba", hours: "10:00 — 19:00" },
      { day: "Perşembe", hours: "10:00 — 19:00" },
      { day: "Cuma", hours: "10:00 — 19:00" },
      { day: "Cumartesi", hours: "10:00 — 17:00" },
    ],
    recentAppointments: [
      { id: "a1", client: "Arda N.", service: "Buzz Cut", time: "10:15" },
      { id: "a2", client: "Ali R.", service: "Yikama", time: "13:20" },
      { id: "a3", client: "Eren O.", service: "Klasik Kesim", time: "17:10" },
    ],
  },
];
